protected/models/PostCategory.php
<?php

/**
 * This is the model class for table "post_category".
 *
 * The followings are the available columns in table 'post_category':
 * @property integer $id
 * @property string $title
 */
class PostCategory extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return PostCategory the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post_category';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>255),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function countPost()
	{
		return Post::model()->countByAttributes(array('post_category_id'=>$this->id));
	}
}

protected/controllers/PostCategoryController.php
<?php

class PostCategoryController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
	public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('read'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','view','index','chartByPostCategory'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/column2';
		
		$model = $this->loadModel($id);
		
		$criteria = new CDbCriteria;
		$criteria->condition = 'post_category_id=:kategori';
		$criteria->params = array(':kategori'=>$id);
		
		$dataProvider=new CActiveDataProvider('Post',array(
			'criteria'=>$criteria
		));
		
		$this->render('read',array(
			'dataProvider'=>$dataProvider,
			'model'=>$model,
		));
	}

	public function actionView($id)
	{	
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}


/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
	public function actionCreate()
	{
		$model=new PostCategory;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PostCategory']))
		{
			$model->attributes=$_POST['PostCategory'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil ditambahkan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PostCategory']))
		{
			$model->attributes=$_POST['PostCategory'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil diperbarui');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('PostCategory');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

	/**
	* Manages all models.
	*/
	
	public function actionAdmin()
	{
		$model=new PostCategory('search');
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['PostCategory']))
			$model->attributes=$_GET['PostCategory'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionChartByPostCategory()
	{
		Yii::app()->fusioncharts->setChartOptions(array(
			'caption'=>'Jumlah Post Berdasarkan Kategori', 
		));
		
		foreach(PostCategory::model()->findAll() as $data) 
		{
			Yii::app()->fusioncharts->addSet(array('label'=>$data->title, 'value'=>$data->countPost()));
		}
		
		Yii::app()->fusioncharts->getXMLData(true);
	}
	
	

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=PostCategory::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='post-category-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('read'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','create','update','view','chartByPostCategory'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
				//'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/column2';
		
		$this->render('read',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	public function actionView($id)
	{
		
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		
		
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			
			$thumbnail = CUploadedFile::getInstance($model,'thumbnail');
			
			if($thumbnail!==null)
				$model->thumbnail = str_replace(' ','-',time().'_'.$thumbnail->name);
			
			date_default_timezone_set('Asia/Jakarta');
			$model->created_time = date('Y-m-d H:i:s');
			
			if($model->save())
			{
				if($thumbnail!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/post/';
					$thumbnail->saveAs($path.$model->thumbnail);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		
		
		$model=$this->loadModel($id);
		
		$old_thumbnail = $model->thumbnail;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			
			$thumbnail = CUploadedFile::getInstance($model,'thumbnail');
			
			if($thumbnail!==null)
				$model->thumbnail = str_replace(' ','-',time().'_'.$thumbnail->name);
			else
				$model->thumbnail = $old_thumbnail;
			
			if($model->save())
			{
				if($thumbnail!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/post/';
					$thumbnail->saveAs($path.$model->thumbnail);
					
					if(file_exists($path.$old_thumbnail) AND $old_thumbnail!='')
						unlink($path.$old_thumbnail);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Post');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionChartByPostCategory()
	{
		Yii::app()->fusioncharts->setChartOptions(array(
			'caption'=>'Jumlah Post Berdasarkan Kategori', 
		));
		
		foreach(PostCategory::model()->findAll() as $data) 
		{
			Yii::app()->fusioncharts->addSet(array('label'=>$data->title, 'value'=>$data->countPost()));
		}
		
		Yii::app()->fusioncharts->getXMLData(true);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/postCategory/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'post-category-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>
	
<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Simpan',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/postCategory/_read.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<div class="row-fluid">
	<div class="row-fluid">
		<div class="span12">
			<h3 class="tittle-inovasi"><?php echo CHtml::link($data->title, array('/post/read','id'=>$data->id));?></h3>
			<div class='post-read-created-time'>
				<?php print Bantu::getWaktuDibuat($data->created_time); ?>
			</div>
		</div>
	</div>
	<div class="row-fluid">
	<div class="span4">
		<?php if($data->thumbnail!='') print $data->getThumbnail(); else print CHtml::image(Yii::app()->request->baseUrl.'/images/logo-lan.png',''); ?>
	</div>
	<div class="span8">
		<?php echo substr($data->content,0,300).'...';?>
		<?php echo CHtml::link('Selanjutnya', array('/post/read','id'=>$data->id));?></p>
	</div>
	</div>
</div>
<hr>
	

protected/views/postCategory/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/postCategory/_thumb.php
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="<?php echo bu('images/placeholder260x180.gif');?>" alt="">
        <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
    </div>
</div>

protected/views/postCategory/_view.php
<div class="view">
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />


</div>

protected/views/postCategory/admin.php
<?php
$this->breadcrumbs=array(
	'Post Categories'=>array('index'),
	'Manage',
);

$this->menu=array(
	//array('label'=>'List PostCategory','url'=>array('index')),
	array('label'=>'Tambah Kategori','url'=>array('create')),
	array('label'=>'Kelola Post','url'=>array('post/admin')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('post-category-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Kelola Kategori Post</h1>

<?php $this->widget('booster.widgets.TbButtonGroup', array(
    'context'=>'primary', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'buttons'=>array(
		array('label'=>'Pilihan Menu','items'=>array(
			array('label'=>'Tambah Kategori','icon'=>'plus','url'=>array('/postCategory/create')),
			array('label'=>'Kelola Post','icon'=>'th-list','url'=>array('/post/admin')),
		)),
    ),
)); ?>


<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'post-category-grid',
		'dataProvider'=>$model->search(),
		'type'=>'striped bordered',
		'filter'=>$model,
		'columns'=>array(
			'title',
			array(
				'class'=>'booster.widgets.TbButtonColumn',
			),
		),
)); ?>

protected/views/postCategory/create.php
<?php
$this->breadcrumbs=array(
	'Post Categories'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'Kelola Kategori','url'=>array('admin')),
	array('label'=>'Kelola Post','url'=>array('admin'),'icon'=>'list'),
);
?>

<h1>Tambah Kategori Post</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/postCategory/index.php
<?php
$this->breadcrumbs=array(
	'Post Categories',
);

$this->menu=array(
array('label'=>'Create PostCategory','url'=>array('create')),
array('label'=>'Manage PostCategory','url'=>array('admin')),
);
?>

<h1>Post Categories</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/postCategory/read.php
<?php
$this->breadcrumbs=array(
	'Posts',
);

$this->menu=array(
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'Manage Post','url'=>array('admin')),
);
?>

<div class="margin20" id="postCategory-read">

<h3 class="list-bottom"><?php print strtoupper($model->title); ?></h3>

<hr>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_read',
)); ?>

</div>

protected/views/postCategory/update.php
<?php
$this->breadcrumbs=array(
	'Post Categories'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	//array('label'=>'List PostCategory','url'=>array('index')),
	array('label'=>'Tambah Kategori','url'=>array('create')),
	array('label'=>'Lihat Kategori','url'=>array('view','id'=>$model->id)),
	array('label'=>'Kelola Kategori','url'=>array('admin')),
	);
	?>

<h1>Sunting Kategori Artikel</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/postCategory/view.php
<?php
$this->breadcrumbs=array(
	'Post Categories'=>array('index'),
	$model->title,
);

$this->menu=array(
	//array('label'=>'List PostCategory','url'=>array('index')),
	array('label'=>'Tambah Kategori','url'=>array('create')),
	array('label'=>'Sunting Kategori','url'=>array('update','id'=>$model->id)),
	array('label'=>'Kelola Kategori','url'=>array('admin')),
	array('label'=>'Hapus Kategori','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Kelola Kategori','url'=>array('admin')),
);
?>

<h1>Lihat Kategori Artikel</h1>


<?php /* $this->widget('booster.widgets.TbButtonGroup', array(
    'type'=>'primary', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'buttons'=>array(
		array('label'=>'Pilihan Menu','items'=>array(
			array('label'=>'Sunting Kategori','icon'=>'pencil','url'=>array('/postCategory/update','id'=>$model->id)),
			array('label'=>'Tambah Kategori','icon'=>'plus','url'=>array('/postCategory/create')),
			array('label'=>'Kelola Kategori','icon'=>'th-list','url'=>array('/post/admin')),
		)),
    ),
)); 

<div>&nbsp;</div>

*/ ?>

<?php $this->widget('booster.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered',
		'attributes'=>array(
			'title',
		),
)); ?>