protected/controllers/PageController.php
<?php

class PageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('read'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view','create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
				//'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->layout = '//layouts/admin/column2';
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/main';
		
		$this->render('read',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$this->layout = '//layouts/admin/column2';
		
		
		$model=new Page;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			
			date_default_timezone_set("Asia/Jakarta");
			$model->time_created = date('y-m-d H:i:s');
			
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->layout = '//layouts/admin/column2';
		
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Page');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$this->layout = '//layouts/admin/column2';
		
		
		$model=new Page('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Page']))
			$model->attributes=$_GET['Page'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Page::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='page-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/page/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'page-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->labelEx($model,'content'); ?>
	<?php $this->widget('ext.editMe.widgets.ExtEditMe', array(
			'model'=>$model,
			'attribute'=>'content',
			'filebrowserImageBrowseUrl'=>  Yii::app()->baseUrl.'/vendors/kcfinder/browse.php',
			'filebrowserImageBrowseLinkUrl'=>Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=images',
			'filebrowserFlashBrowseUrl' => Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=Flash',
	)); ?>
	<?php echo $form->error($model,'content'); ?> 
	
	<div>&nbsp;</div>
	
	<div class="form-actions">
		<?php print CHtml::submitButton('Save'); ?>
		<?php /* $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>$model->isNewRecord ? 'Simpan' : 'Simpan',
		)); ?>
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'link',
			'url'=>array('page/admin'),
			'context'=>'primary',
			'icon'=>'list white',
			'label'=>'Kelola',
		)); */ ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/page/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/page/_video.php
<?php
	$video = PageVideo::model()->findByAttributes(array('page_id'=>$model->id));
	
	if($video===null)
	{
		$video = new PageVideo;
		$video->page_id = $model->id;
		$video->save();
	}

?>

<?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
    'type'=>'primary', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'buttons'=>array(
		array('label'=>'Pilihan Menu','items'=>array(
			array('label'=>'Sunting Video','icon'=>'pencil','url'=>array('/pageVideo/update','id'=>$video->id)),
		)),
    ),
)); ?>


<div>&nbsp;</div>

<table class='table table-bordered table-striped'>
<tr>
	<th>MP4</th>
	<td>
		<?php if($video->mp4!='') { ?>
		<?php $this->widget('application.extensions.videojs.EVideoJS', array(
				'options' => array(
					'id' => false,
					'width' => 360,
					'height' => 270,
					'poster' => "http://localhost/pu-babel/images/playvido.png",
					'video_mp4' => Yii::app()->request->baseUrl."/uploads/pekerjaan/".$video->mp4,
					'video_ogv' => false,
					'video_webm' => false,
					'flash_fallback' => true,
					'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
					'controls' => true,
					'preload' => true,
					'autoplay' => false,
					'support' => true,
					'download' => false,
				),
		)); ?>
		<?php } ?>
	</td>
</tr>
<tr>
	<th>OGV</th>
	<td>
		<?php if($video->ogv!='') { ?>
		<?php $this->widget('application.extensions.videojs.EVideoJS', array(
				'options' => array(
					'id' => false,
					'width' => 360,
					'height' => 270,
					'poster' => "http://localhost/pu-babel/images/playvido.png",
					'video_mp4' => false,
					'video_ogv' => Yii::app()->request->baseUrl."/uploads/pekerjaan/".$video->ogv,
					'video_webm' => false,
					'flash_fallback' => true,
					'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
					'controls' => true,
					'preload' => true,
					'autoplay' => false,
					'support' => true,
					'download' => false,
				),
		)); ?>
		<?php } ?>
	</td>
</tr>
<tr>
	<th>WebM</th>
	<td>
		<?php if($video->webm!='') { ?>
		<?php $this->widget('application.extensions.videojs.EVideoJS', array(
				'options' => array(
					'id' => false,
					'width' => 360,
					'height' => 270,
					'poster' => "http://localhost/pu-babel/images/playvido.png",
					'video_mp4' => false,
					'video_ogv' => false,
					'video_webm' => Yii::app()->request->baseUrl."/uploads/pekerjaan/".$video->webm,
					'flash_fallback' => true,
					'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
					'controls' => true,
					'preload' => true,
					'autoplay' => false,
					'support' => true,
					'download' => false,
				),
		)); ?>
		<?php } ?>
	</td>
</tr>
</table>

protected/views/page/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />


</div>

protected/views/page/admin.php
<?php
$this->breadcrumbs=array(
	'Pages'=>array('index'),
	'Manage',
);


Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('page-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Kelola Page</h1>

<?php //$this->widget('booster.widgets.TbButton',array('buttonType'=>'link','context'=>'primary','icon'=>'plus white','label'=>'Tambah','url'=>array('page/create'))); ?>

<?php print CHtml::link(Chtml::submitButton('Tambah'),array('page/create')); ?>

<?php $this->widget('booster.widgets.TbGridView',array(
	'id'=>'page-grid',
	'dataProvider'=>$model->search(),
	'type'=>'striped bordered',
	'filter'=>$model,
	'columns'=>array(
		'title',
		'time_created',
		array(
			'class'=>'booster.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/page/create.php
<?php
$this->breadcrumbs=array(
	'Laman'=>array('admin'),
	'Tambah',
);


?>

<h1>Tambah Page</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/page/index.php
<?php
$this->breadcrumbs=array(
	'Pages',
);

$this->menu=array(
	array('label'=>'Create Page','url'=>array('create')),
	array('label'=>'Manage Page','url'=>array('admin')),
);
?>

<h1>Pages</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/page/read.php
<h1><?php print strtoupper($model->title); ?></h1>

<div class="container">
	<div class="col-lg-2 col-md-2">&nbsp;</div>
	<div class="col-lg-8 col-md-8">
		<?php print $model->content; ?>
	</div>
	<div class="col-lg-2 col-md-2">&nbsp;</div>
</div><!-- welcome message -->

<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

protected/views/page/update.php
<?php
$this->breadcrumbs=array(
	'Pages'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

?>

<h1>Sunting Laman</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/page/view.php
<?php
$this->breadcrumbs=array(
	'Pages'=>array('index'),
	$model->title,
);

?>

<h1>Lihat Laman</h1>

<?php print CHtml::link(Chtml::submitButton('Sunting'),array('page/update','id'=>$model->id)); ?>&nbsp;
<?php print CHtml::link(Chtml::submitButton('Kelola Page'),array('page/admin')); ?>



<?php /* $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Sunting',
		'context'=>'primary',
		'icon'=>'pencil white',
		'url'=>array('/page/update','id'=>$model->id)
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Baca',
		'context'=>'primary',
		'icon'=>'search white',
		'url'=>array('/page/read','id'=>$model->id),
		'htmlOptions'=>array('target'=>'_blank')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/page/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Kelola',
		'context'=>'primary',
		'icon'=>'list white',
		'url'=>array('/page/admin')
)); */ ?>

<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
	'data'=>$model,
	'type'=>'striped bordered',
	'attributes'=>array(
		'title',
		array(
			'label'=>'Content',
			'type'=>'raw',
			'value'=>$model->content
		),
		array(
			'label'=>'Url',
			'type'=>'raw',
			'value'=>$this->createUrl('page/read',array('id'=>$model->id))
		),
		'time_created',
	),
)); ?>