protected/models/Portfolio.php
<?php

/**
 * This is the model class for table "portfolio".
 *
 * The followings are the available columns in table 'portfolio':
 * @property integer $id
 * @property string $title
 * @property integer $portfolio_category_id
 * @property string $client
 * @property string $description
 * @property string $image
 */
class Portfolio extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'portfolio';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, portfolio_category_id, client', 'required'),
			array('portfolio_category_id', 'numerical', 'integerOnly'=>true),
			array('title, client, image', 'length', 'max'=>255),
			array('description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, portfolio_category_id, client, description, image', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'PortfolioCategory'=>array(self::BELONGS_TO,'PortfolioCategory','portfolio_category_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'portfolio_category_id' => 'Portfolio Category',
			'client' => 'Client',
			'description' => 'Description',
			'image' => 'Image',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('portfolio_category_id',$this->portfolio_category_id);
		$criteria->compare('client',$this->client,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('image',$this->image,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Portfolio the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function getThumbnail($htmlOptions=array())
	{
		return CHtml::image(Yii::app()->request->baseUrl.'/uploads/portfolio/'.$this->image,'',$htmlOptions);
	}
	
	public function getLatestProject($category_id=null,$limit=3)
	{
		if($category_id!=null)
		{
			$model = Portfolio::model()->findAllByAttributes(array('portfolio_category_id'=>$category_id),array('order'=>'id ASC','limit'=>$limit));
		} else {
			$model = Portfolio::model()->findAll(array('order'=>'id ASC','limit'=>$limit));
		}
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getDataPortfolioImage()
	{
		$model = PortfolioImage::model()->findAllByAttributes(array('portfolio_id'=>$this->id),array('order'=>'id ASC'));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getLatestByCategory($category)
	{
		if($category!=null) {
			return Portfolio::model()->findAllByAttributes(array('portfolio_category_id'=>$category),array('order'=>'id DESC'));
		} else {
			return Portfolio::model()->findAll(array('order'=>'id DESC'));			
		}
	}
	
	public function getPortfolioforRead($id)
	{	
		return Portfolio::model()->findByAttributes(array('id'=>$id));
	}
	
	public function getPortfolioImageforRead($id)
	{
		$model = PortfolioImage::model()->findAllByAttributes(array('portfolio_id'=>$id),array('order'=>'id DESC'));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getCarouselImage()
	{
		$image = array();
		
		foreach(PortfolioImage::model()->findAllByAttributes(array('portfolio_id'=>$this->id)) as $data)
		{
			array_push($image,array('image'=>Yii::app()->baseUrl.'/uploads/portfolioImage/'.$data->file));
		}
		
		return $image;
	}
}

protected/controllers/PortfolioController.php
<?php

class PortfolioController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','read'),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('create','update','view'),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete'),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($id)
	{
		$this->render('view',array(
		'model'=>$this->loadModel($id),
		));
	}
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/main';
		
		$this->render('read',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionCreate()
	{
		$model=new Portfolio;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Portfolio']))
		{
			$model->attributes=$_POST['Portfolio'];
			
			$image = CUploadedFile::getInstance($model,'image');
			
			if($image!==null)
				$model->image = str_replace(' ','-',time().'_'.$image->name);
			
			if($model->save())
			{
				if($image!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/portfolio/';
					$image->saveAs($path.$model->image);
				}
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		$old_thumbnail = $model->image;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Portfolio']))
		{
			$model->attributes=$_POST['Portfolio'];
			
			$image = CUploadedFile::getInstance($model,'image');
			
			if($image!==null)
				$model->image = str_replace(' ','-',time().'_'.$image->name);
			else
				$model->image = $old_thumbnail;
			
			if($model->save())
			{
				if($image!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/portfolio/';
					$image->saveAs($path.$model->image);
					
					if(file_exists($path.$old_thumbnail) AND $old_thumbnail!='')
						unlink($path.$old_thumbnail);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	* Lists all models.
	*/
	public function actionIndex($category=null)
	{
		$this->layout = '//layouts/main';
		
		$criteria=new CDbCriteria(array(                    
            'order'=>'id DESC',
            'condition'=>'portfolio_category_id='.$category.'',
        ));
		
		if($category!=null) 
		{
			$dataProvider=new CActiveDataProvider('Portfolio', array(
				'criteria'=>$criteria,
				'pagination'=>array(
					'pageSize'=>9,
					'itemCount'=>9
				)
			));
		}
		if($category==null) 
		{
			$dataProvider=new CActiveDataProvider('Portfolio',array('pagination'=>array(
				'pageSize'=>9,
				'itemCount'=>9
				)
			));
		}
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Portfolio('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Portfolio']))
$model->attributes=$_GET['Portfolio'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Portfolio::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='portfolio-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/portfolio/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'portfolio-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data')
)); ?>

<p class="help-block">Kolom dengan tanda <span class="required">*</span> wajib diisi.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->dropDownListGroup($model,'portfolio_category_id',array('widgetOptions'=>array('data'=>CHtml::listData(PortfolioCategory::model()->findAll(),'id','title'),'htmlOptions'=>array('class'=>'span5')))); ?>
	
	<?php echo $form->textFieldGroup($model,'client',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->labelEx($model,'description'); ?>
	<?php $this->widget('ext.editMe.widgets.ExtEditMe', array(
			'model'=>$model,
			'attribute'=>'description',
			'filebrowserImageBrowseUrl'=>  Yii::app()->baseUrl.'/vendors/kcfinder/browse.php',
			'filebrowserImageBrowseLinkUrl'=>Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=images',
			'filebrowserFlashBrowseUrl' => Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=Flash',
	)); ?>
	<?php echo $form->error($model,'description'); ?> 
	
	<div>&nbsp;</div>
	<?php print $form->labelEx($model,'image'); ?>
	<?php if(!empty($model->image)) print CHtml::image(Yii::app()->request->baseUrl.'/uploads/portfolio/'.$model->image); ?>
	<?php echo $form->fileField($model,'image',array('class'=>'span5','maxlength'=>255)); ?>
	<?php print $form->error($model,'image'); ?>
	
	<div>&nbsp;</div>
	
<div class="form-actions">
	<?php print CHtml::submitButton('Save'); ?>
	<?php /* $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok',
			'label'=>$model->isNewRecord ? 'Simpan' : 'Simpan',
		)); */ ?>
</div>

<?php $this->endWidget(); ?>

protected/views/portfolio/_menu_item.php
<tr>
	<td style="padding-left:<?php print $level*30; ?>px">
		<?php $this->widget('booster.widgets.TbButtonGroup', array(
				'context'=>'primary',
				'size'=>'small',
				'buttons'=>array(
					array('label'=>'','items'=>array(
						array('label'=>'Update','icon'=>'pencil','url'=>array('portfolioImage/update','id'=>$data->id)),
					)),
				),
		)); ?>
		<?php print $data->title; ?></td>
	<td>
		<?php print CHtml::link('<i class="icon-pencil"></i>',array('pollingChoice/update','id'=>$data->id)); ?>
		<?php print CHtml::link('<i class="icon-trash"></i>','#',array('submit'=>array('pollingChoice/delete','id'=>$data->id),'params'=>array('returnUrl'=>$this->createUrl('polling/view',array('id'=>$model->id))),'confirm'=>'Yakin akan menghapus data?')); ?>
	</td>
</tr>

protected/views/portfolio/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'portfolio_category_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'client',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textAreaGroup($model,'description', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

		<?php echo $form->textFieldGroup($model,'image',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/portfolio/_view.php
<div class="col-lg-4 col-md-4">
	<div class="view">
		<div class="project-carousel">
		<div class="project-item">
		<?php $referralImg = CHtml::image(Yii::app()->baseUrl."/uploads/portfolio/".$data->image."","",array("class"=>"img-circle","width"=>"250px")); 
			echo CHtml::link($referralImg,array('portfolio/read','id'=>$data->id)); ?>
			<div>&nbsp;</div>
			<div class="category-carousel"><b>Category : </b><?php print $data->PortfolioCategory->title ?></div>
			<div>&nbsp;</div>
			<div class="client-carousel"><b>Client : </b><?php print $data->client ?></div>
		</div>
		</div>
	</div>
</div>

protected/views/portfolio/admin.php
<?php
$this->breadcrumbs=array(
	'Portfolio'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Portfolio','url'=>array('index')),
array('label'=>'Create Portfolio','url'=>array('create')),
);
?>

<h1>Kelola Portfolio</h1>

<?php print CHtml::link(Chtml::submitButton('Tambah'),array('portfolio/create')); ?>


<?php /*$this->widget('booster.widgets.TbButton',array(
			'buttonType'=>'link',
			'context'=>'primary',
			'icon'=>'plus white',
			'label'=>'Tambah',
			'url'=>array('portfolio/create')
		)); ?>&nbsp;
		
<?php $this->widget('booster.widgets.TbButton',array(
			'buttonType'=>'link',
			'context'=>'primary',
			'icon'=>'list white',
			'label'=>'Kategori',
			'url'=>array('portfolioCategory/admin')
		)); */ ?>&nbsp;

<?php $this->widget('booster.widgets.TbGridView',array(
'id'=>'portfolio-grid',
'type'=>'striped bordered',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
		'title',
		array(
			'class'=>'CDataColumn',
			'name'=>'portfolio_category_id',
			'header'=>'Kategori',
			'value'=>'$data->PortfolioCategory->title',
			'filter'=>CHtml::listData(PortfolioCategory::model()->findAll(),'id','title')
		),
		'client',
		array(
			'class'=>'CDataColumn',
			'name'=>'image',
			'type'=>'raw',
			'value'=>'$data->getThumbnail(array("width"=>"400px"))'
		),
array(
'class'=>'booster.widgets.TbButtonColumn',
),
),
)); ?>

protected/views/portfolio/create.php
<?php
$this->breadcrumbs=array(
	'Portfolio'=>array('index'),
	'Create',
);
?>

<h1>Tambah Portofolio</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/portfolio/index.php
<div class="container" style="width:950px">
	<div class="row">
		<div class="col-lg-12 col-md-12 portofolio-index">
			<h3>PORTOFOLIO</h3>
		</div>
	</div>
	<div class="row portofolio-index">
		<div class="col-lg-1 col-md-1">
			&nbsp;
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-video71"></i>',
				array('portfolio/index','category'=>1), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'VIDEOGRAPHY')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-dslr"></i>',
				array('portfolio/index','category'=>2), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'PHOTOGRAPHY')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-palette5"></i>',
				array('portfolio/index','category'=>3), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'GRAPHIC DESIGN')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-drawing10"></i>',
				array('portfolio/index','category'=>4), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'ILLUSTRATION')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-screen52"></i>',
				array('portfolio/index','category'=>5), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'WEB DESIGN')) 
			?>
		</div>
		<div class="col-lg-1 col-md-1">
			&nbsp;
		</div>
	</div>
	<div class="row portofolio-content">
			<?php $this->widget('booster.widgets.TbListView',array(
				'dataProvider'=>$dataProvider,
				'itemView'=>'_view',
			)); ?>
	</div>
</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

protected/views/portfolio/read.php
<div class="container" style="width:950px">
	<div class="row">
		<div class="col-lg-12 col-md-12 portofolio-index">
			<h3>PORTOFOLIO</h3>
		</div>
	</div>
	<div class="row portofolio-index">
		<div class="col-lg-1 col-md-1">
			&nbsp;
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-video71"></i>',
				array('portfolio/index','category'=>1), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'VIDEOGRAPHY')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-dslr"></i>',
				array('portfolio/index','category'=>2), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'PHOTOGRAPHY')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-palette5"></i>',
				array('portfolio/index','category'=>3), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'GRAPHIC DESIGN')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-drawing10"></i>',
				array('portfolio/index','category'=>4), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'ILLUSTRATION')) 
			?>
		</div>
		<div class="col-lg-2 col-md-2 category-icon">
			<?php echo CHtml::link('<i class="flaticon-screen52"></i>',
				array('portfolio/index','category'=>5), 
				array('data-toggle'=>'tooltip','data-placement'=>'bottom','title'=>'WEB DESIGN')) 
			?>
		</div>
		<div class="col-lg-1 col-md-1">
			&nbsp;
		</div>
	</div>
	<div>&nbsp;</div>
	
	<div class="row">
		<div class="col-lg-8 col-md-8 portofolio-carousel-image">
			<?php $this->widget('booster.widgets.TbCarousel',array(
					'items' => $model->getCarouselImage(),
			)); ?>
		<?php /*
		<div class="index-carousel" style="margin-top:10px">
			<?php foreach(Portfolio::model()->getPortfolioImageforRead($_GET['id']) as $data) { ?>
				<?php print CHtml::image(Yii::app()->baseUrl."/uploads/portfolioImage/".$data->file."","",array("class"=>"","width"=>"600px")); ?>
			<?php } ?>
		</div>
		*/ ?>
		</div>
		<div class="col-lg-4 col-md-4 portofolio-carousel-description">
			<?php $content = Portfolio::model()->getPortfolioforRead($_GET['id']) ?>
			<div class="index-content">
				<h3 style="margin-top:0px;"><?php print $content->title ?></h3>
				<div>&nbsp;</div>
				<div><b>Category</b> : </b><?php print $content->PortfolioCategory->title ?></div>
				<div><b>Client</b> : </b><?php print $content->client ?></div>
				<div>&nbsp;</div>
				<div>
					<?php print $content->description ?>
				</div>
			</div>
		</div>
		<?php /* $this->widget('ext.carouFredSel.ECarouFredSel', array(
					'id' => 'carousel',
					'target' => '.index-carousel',
					'config' => array(
						'auto' => array(
							'play' =>true
						),
						'items'=>1,
						'scroll'=>array(
							'fx'=>'crossfade',
							'items'=>1,
							'pauseOnHover'=>false
						),
						'pagination'=>array(
							'items'=>1
						)
					)
		)); */ ?>
	</div>
</div>

<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

protected/views/portfolio/update.php
<?php
$this->breadcrumbs=array(
	'Portfolios'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Portfolio','url'=>array('index')),
	array('label'=>'Create Portfolio','url'=>array('create')),
	array('label'=>'View Portfolio','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Portfolio','url'=>array('admin')),
	);
	?>

	<h1>Update Portfolio <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/portfolio/view.php
<?php
$this->breadcrumbs=array(
	'Portfolios'=>array('index'),
	$model->title,
);
?>

<h1>Lihat Portofolio</h1>

<?php print CHtml::link(Chtml::submitButton('Sunting'),array('portfolio/update','id'=>$model->id)); ?>&nbsp;
<?php print CHtml::link(Chtml::submitButton('Kelola'),array('portfolio/admin')); ?>

<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'type'=>'striped bordered',
'attributes'=>array(
		'title',
		array(
			'label'=>'Kategori',
			'value'=>$model->PortfolioCategory->title
		),
		'client',
		array(
			'label'=>'Deskripsi',
			'type'=>'raw',
			'value'=>$model->description
		),
		array(
			'label'=>'Image',
			'type'=>'raw',
			'value'=>$model->image == '' ? '' : CHtml::image(Yii::app()->request->baseUrl.'/uploads/portfolio/'.$model->image,'',array('width'=>'600px'))
		),
),
)); ?>

<div>&nbsp;</div>

<h2>Image Portofolio</h2>

<?php print CHtml::link(Chtml::submitButton('Add Image'),array('portfolioImage/create','portfolio_id'=>$model->id)); ?>

<?php /* $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'link',
			'context'=>'primary',
			'label'=>'Add Image',
			'icon'=>'plus',
			'url'=>array('portfolioImage/create','portfolio_id'=>$model->id,)
)); */ ?>

<div>&nbsp;</div>

<table class="table">
<tr>
	<th>No</th>
	<th>Title</th>
	<th>Image</th>
	<th>Action</th>
</tr>
<?php $i=1; foreach($model->getDataPortfolioImage() as $data) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $data->title; ?></td>
	<td><?php print CHTml::image(Yii::app()->baseUrl."/uploads/portfolioImage/".$data->file); ?></td>
	<td>
		<a href="<?php print $this->createUrl("portfolioImage/update",array("id"=>$data->id)); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
		<a href="<?php print $this->createUrl("portfolioImage/directDelete",array("id"=>$data->id)); ?>" onclick="return confirm('Yakin akan menghapus file?')"><i class="glyphicon glyphicon-trash"></i></a>
	</td>
</tr>
<?php $i++; } ?>
</table>